// <auto-generated />
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250505204427_Init-2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entities.ForbiddenEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Alcohol")
                        .HasColumnType("bit");

                    b.Property<bool>("Bike")
                        .HasColumnType("bit");

                    b.Property<bool>("Camera")
                        .HasColumnType("bit");

                    b.Property<bool>("Hazard")
                        .HasColumnType("bit");

                    b.Property<bool>("Knife")
                        .HasColumnType("bit");

                    b.Property<bool>("Merch")
                        .HasColumnType("bit");

                    b.Property<bool>("Noise")
                        .HasColumnType("bit");

                    b.Property<bool>("Pets")
                        .HasColumnType("bit");

                    b.Property<bool>("Picnic")
                        .HasColumnType("bit");

                    b.Property<bool>("Pill")
                        .HasColumnType("bit");

                    b.Property<bool>("Tent")
                        .HasColumnType("bit");

                    b.Property<bool>("Umbrella")
                        .HasColumnType("bit");

                    b.HasKey("EventId");

                    b.ToTable("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
